### ISSUE TITLE
actors are not drawn in entity order

### ISSUE THREAD

**Issue by floybix** [oakes/play-clj#80]
Hi

I've run into a problem in the latest version: I have a Shape (a speech bubble) which is supposed to have a Label drawn on top of it - since the label appears later in the entity vector. But now it is drawn behind. I've traced this to the commit 2461718 "don't draw actors twice", which uses the Stage draw function for all entities -- before any other entities are drawn -- rather than `draw!`ing each entity in the vector.

Doesn't seem to be any way around it. Can we skip the Stage `.draw` and use the Entity `draw!` instead?

Or is there another way? perhaps turning the Shape into an Actor and setting the z-index?

**Comment by oakes** [comment]
Yeah I knew this might be an issue, but I was hoping it wasn't a common thing. The workaround is to use `(render! screen) (draw! screen entities)` separately instead of `(render! screen entities)`. I will try to find a better solution in the next version, so the second method works as well.

I tried skipping Stage's `.draw` but found that it causes problems. You can see this by making that change and testing the ui-gallery example app.

**Comment by floybix** [comment]
I see, thanks.

**Comment by oakes** [comment]
I have released 0.4.6 which reverts the change in question.
