### ISSUE TITLE
Why so many macros?

### ISSUE THREAD

**Issue by jbeja** [oakes/play-clj#88]
First of all, awesome library!

I am a beginner to Clojure and learning for the source code I have seem so many even in case where I don't see that there isn't any benefit, am I missing something here?

**Comment by oakes** [comment]
Hello. My library definitely has more macros than most. The reason is that I wanted to provide a convenient syntax for using libGDX classes. For example, the following code...

```clojure
(texture "clojure.png"
  :flip true false
  :set-region 0 0 100 100)
```

...is transformed at compile-time to this:

```clojure
(let [entity (texture* "clojure.png")]
  (doto ^TextureRegion (:object entity)
    (.flip true false)
    (.setRegion 0 0 100 100))
  entity)
```

It makes it a lot more terse and readable. I wanted to provide this functionality for more than just the `TextureRegion` class, so I made a separate macro for each class that I wanted this functionality for.

**Comment by jbeja** [comment]
Oh I see, make sense now. Thanks for answering.
